
name: Test

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  test:
    strategy:
      matrix:
        sys:
          - { os: windows-latest, shell: "C:/msys64/usr/bin/bash.exe -e {0}" }
          - { os: ubuntu-latest, shell: bash }
          - { os: macos-latest, shell: bash }
    name: Test ${{ matrix.sys.os }}
    runs-on: ${{ matrix.sys.os }}
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}
    steps:

      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2

      - run: cabal build all

      - run: 'eval $(cabal list-bin mergify-hacking | tr \\ /)'
